name: PullRequestOpenedOrUpdated
run-name: ${{ github.event.client_payload.sender.login }} has opened, reopened or added commits to a PR
on:
  repository_dispatch:
    types: [PullRequestOpenedOrUpdated]

jobs:
  UnitTests:
    uses: ./.github/workflows/RunUnitTests.yml
    with:
      pr-number: ${{ github.event.client_payload.pull_request.number }}
      pr-repo: ${{ github.event.client_payload.repository.full_name }}
    secrets: inherit
    