name: PullRequestComment
run-name: ${{ github.event.client_payload.sender.login }} has added a PR comment
# PR comments are reported via issue_comments
on:
  repository_dispatch:
    types: [PullRequestComment]

env:
  KEYWORD_REGEX: (check|recheck|regate|pregate)

jobs:
  CheckForKeywords:
  # Only run if the comment was on a PR
    if: ${{ github.event.client_payload.issue.pull_request }}
    runs-on: ubuntu-latest
    outputs:
      keyword: ${{ steps.parse.outputs.keyword }}
    steps:
      - name: DumpEnvironment
        uses: /asterisk/asterisk-ci-actions/DumpEnvironmentAction@main

      - name: ParseComment
        id: parse
        env:
          BODY: ${{ github.event.client_payload.comment.body }}
        run: |
          echo "::group::comment_body"
          echo $BODY
          echo "::endgroup::"
          # Find the first match in the comment
          kw=$(echo $BODY | sed -n -r -e "0,/^\s*${KEYWORD_REGEX}\s*$/s//keyword=\1/p")
          echo $kw >> "$GITHUB_OUTPUT"
          echo "::notice::KW: $kw" 
          exit 0
          
  UnitTests:
    needs: CheckForKeywords
    if: endsWith(needs.CheckForKeywords.outputs.keyword, 'check')
    uses: ./.github/workflows/RunUnitTests.yml
    with:
      pr-number: ${{ github.event.client_payload.issue.number }}
      pr-repo: ${{ github.event.client_payload.repository.full_name }}
    secrets: inherit

